#!/bin/sh
#
# start the xscreensaver daemon if need be, then lock the screen
#
# This fiddling around is a workaround to the problem, already locked and fails to lock.

if ! xscreensaver-command -lock; then
    xscreensaver-command -exit
    sleep 1
    xscreensaver -nosplash &
    sleep 1
    xscreensaver-command -lock
fi
