#!/usr/bin/env sh

exec nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.xmonad pkgs.xmonad-extras pkgs.xmonad-contrib])" xmobar dmenu trayer networkmanagerapplet udiskie xscreensaver dunst libnotify light pasystray scrot sxiv gnome3.gnome-terminal termonad-with-packages cantarell-fonts xorg.xmodmap arandr skippy-xd libsecret gnome.seahorse --command "$*"
