#!/usr/bin/env sh

exec nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.xmonad pkgs.xmonad-extras pkgs.xmonad-contrib])" xmobar dmenu trayer networkmanagerapplet udiskie xscreensaver dunst libnotify volnoti --command "$*"
