#!/usr/bin/env bash

test -r .Xresources && xrdb -merge .Xresources

xsetroot -solid gray30

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x000000 --height 25 --monitor 1 &

xscreensaver -no-splash &

dunst -config ~/.dunstrc &

# GNOME keyring daemon is started at the system level, for integration with PAM,
# but we need to enable the components we need here, to get ssh.
eval $(gnome-keyring-daemon -s -c ssh,secrets)
export SSH_AUTH_SOCK

nm-applet &

udiskie --tray &

pasystray &

# for xmonad
export NIX_GHC=`which ghc`
exec xmonad
