#!/bin/bash

test -r .Xresources && xrdb -merge .Xresources

xsetroot -solid gray30

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x000000 --height 25 &

xscreensaver -no-splash &

#test -x /usr/bin/nm-applet && nm-applet --sm-disable &

# volume notification daemon
volnoti -t 2

# wait for trayer to start
sleep 1
